### PR TITLE
Fix test build warnings

### PR DESCRIPTION
**Pull request by lieuwex**

### CODE REVIEW

**Comment by tomsmeding** [comment]
I understand nothing anymore about when stuff gives warnings and when it doesn't. In almost all cases, code that compiles without warnings with clang will probably give some warnings on gcc, but then sometimes things are the other way around. ¯\_(ツ)_/¯

**Comment by lieuwex** [comment]
Well this warning was just because you were comparing types with different sizes. And I don't see why this patch would introduce a warning.

**Comment by tomsmeding** [comment]
No but my point is, this is one of the rare cases where clang gives a warning where gcc didn't.
Forgot to merge tho, will do that now

**Comment by lieuwex** [comment]
Oh yeah, it is :P
I thought you didn't want to merge it.

**Comment by lieuwex** [comment]
But it's also a safe comparison so I don't know why clang complains.

**Pull request merged**
